#version 450
#extension GL_ARB_separate_shader_objects : enable

#define MATRIX_SIZE 64
#define WORKGROUP_SIZE 32
layout (local_size_x = WORKGROUP_SIZE, local_size_y = WORKGROUP_SIZE, local_size_z = 1 ) in;

layout(std140, binding = 0) buffer buf
{
   float matrixA[];
};

void main()
{
  uint index = MATRIX_SIZE * gl_GlobalInvocationID.y + gl_GlobalInvocationID.x;
  float PI = 3.1415926535;
  matrixA[index] = exp(PI);
}